blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/muhittincamdali/iOS-Performance-Optimization-Toolkit#readme
    about: Check out the documentation first
  - name: ðŸ’¬ Discussions
    url: https://github.com/muhittincamdali/iOS-Performance-Optimization-Toolkit/discussions
    about: Ask questions and discuss ideas
